---
title: "___"
author: "Amazone Pouillard, Hugo De Smet, Richard Dumont, Solène Joris "
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
link-citations: true
---

<!--# Ce travail doit faire entre 15 et 20 pages.-->

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

Au début de l’année 2020, la Belgique et le reste du monde furent confrontés à une situation sanitaire sans précédent. En Belgique, le pays passa pour la première fois, en temps de paix moderne, par un confinement quasi total des infrastructures non essentielles. Les premières mesures furent annoncées le 12 mars 2020, mais c’est le **18 mars 2020** que le gouvernement décréta un **confinement généralisé**, toutes les activités non essentielles furent fermées, les déplacements limités aux motifs essentiels (achats alimentaires, soins, urgences, ...), et le télétravail rendu prioritaire [@unric_belgique_confinement_2020; @rtbf_confinement_2020].

À l’automne, la deuxième vague pandémique toucha le pays, entraînant le **2 novembre 2020** l’instauration d’un **confinement renforcé**, plus souple que celui du printemps [@rtbf_reconfinement_2020]. Les mesures **restrictives furent maintenues jusqu’au fin-printemps 2021**, avec un allègement progressif selon l’évolution de la situation sanitaire et l’état de vaccination de la population.

## But

<!--% Rédigez le but de ce rapport.-->

Le but de ce rapport est de quantifier et de comparer la fréquentation de ces lieux entre jours de semaine et week-ends en Wallonie durant la pandémie (et plus précisémment de 2020 à 2021), à l’aide d’analyses de séries spatio-temporelles.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter le données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

### Données employées

Les données analysées proviennent des Google COVID-19 Community Mobility Reports, qui fournissent des indicateurs de l’évolution de la fréquentation de différents types de lieux, dont la Wallonie en Belgique [@google_mobility]. Elles sont accessibles librement sous forme de fichiers CSV et couvrent la période du 15 février 2020 au 15 octobre 2022.

Les variations quotidiennes sont exprimées en pourcentage par rapport à un niveau de référence propre à chaque jour de la semaine. Cette référence correspond à la médiane des valeurs observées entre le 3 janvier et le 6 février 2020 [@google_documentation].

Dans ce travail, nous nous focalisons principalement sur les années 2020 et 2021, à partir du premier confinement ordonné par le gouvernement belge le 18 mars 2020 [@unric_belgique_confinement_2020], afin de suivre les périodes de confinement, de post-confinement et les perturbations de mobilité directement liées aux restrictions COVID-19. L’année 2022 est utilisée comme témoin d’une situation progressivement stabilisée post-pandémie.

Parmi les indicateurs disponibles, nous retenons quatre catégories de lieux : commerces et loisirs (retail), parcs, lieux de travail (workplaces) et épiceries/pharmacies (grocery & pharmacy). Pour étudier les différences de comportements, les séries ont été déclinées en sous-ensembles distinguant les week-ends (samedi–dimanche) des jours de semaine (lundi–vendredi), et annotées en fonction des périodes de vacances scolaires en Fédération Wallonie-Bruxelles (carnaval, Pâques, été, Toussaint, hiver) \[\@.. références à insérer + tard\].

### Analyses réalisées et logiciels employés

L’ensemble des analyses a été réalisé dans la SciViews Box 2025 sur la plateforme Saturn Cloud, à l’aide du logiciel R et de l’environnement SciViews::R. Les séries temporelles ont été manipulées et étudiées à l’aide notamment du package pastecs (r packageVersion("pastecs")), ainsi que des fonctions de base de R pour les objets ts.

Pour chaque catégorie de lieu, les pourcentages de variation ont d’abord été convertis en séries temporelles journalières (ts, fréquence = 365, début = 15 février 2020). Nous avons réalisé :

1\) Une visualisation exploratoire des séries brutes, avec ajout de lignes verticales aux dates de confinement et de bandes colorées pour les périodes de vacances scolaires, afin de situer les principaux événements contextuels dans le temps.

2\) Une analyse de la saisonnalité hebdomadaire, en extrayant la composante saisonnière à l’aide de la décomposition de séries temporelles (tsd, avec estimation de la tendance et de la composante saisonnière) puis en représentant le cycle moyen sur plusieurs semaines.

3\) Une analyse spectrale (périodogramme lissé via spectrum et cumulative periodogram via cpgram) pour identifier les fréquences dominantes (comme le cycle hebdomadaire) et vérifier que la saisonnalité constitue bien la structure principale des séries.

4\) Une agrégation hebdomadaire des séries journalières à l’aide de la fonction aggregate et de la moyenne pondérée, afin de lisser les fluctuations quotidiennes et de mettre en évidence les tendances à plus long terme.

5\) Une séparation des dynamiques de semaine et de week-end, en construisant trois versions de chaque série : la série complète, une série ne conservant que les week-ends (jours de semaine remplacés par NA puis agrégation hebdomadaire), une série ne conservant que les jours de semaine (week-ends remplacés par NA puis agrégation hebdomadaire).

Ces différentes étapes ont été appliquées de manière similaire aux catégories commerces et loisirs, parcs, lieux de travail et épiceries/pharmacies, afin de comparer systématiquement l’évolution de la mobilité entre week-ends et jours de semaine pour chacun de ces types de lieux.

## Résultats

<!--% Présentez les analyses les plus pertinents que vous avez sélectionnés. Structurez la section en partie avec des titres explicites de niveau trois.-->

### Impact sur le travail

### Impact sur le commerce

### Analyse de l'impact sur les parcs 

Cette section reprend l'analyse de l'influence du COVID-19, nottament des deux confinements ainsi que celle des vacances scolaires sur les parcs nationaux, les plages publiques, les marinas, les parcs canins, les places et les jardins publics.

#### Analyse générale de la série

```{r}
# Aggrégation par moyenne des valeurs par semaine
parks_ts_agg <- aggregate(parks_ts, 52, FUN = collapse::fmean, ts.eps = 1/52)


plot(parks_ts_ag, 
     main = "Série journalière aggrégée ", xlab = "Temps [année]",
     ylab = "Mobilité vers les parcs, plages et jardins publics (% par rapport à la référence)", ylim = c(-80,400))

# Convertir la date en position sur l'axe x (fraction de l'année)
x_vert <- 2020 + as.numeric(as.Date("2020-03-18") - as.Date("2020-01-01"))/365
abline(v = x_vert, col = "red", lwd = 1, lty = 2)
x_blue <- 2020 + as.numeric(as.Date("2020-11-02") - as.Date("2020-01-01"))/365
abline(v = x_blue, col = "blue", lwd = 1, lty = 2)

# Ajouter un encadrement pour les vacances hiver
## Ajouter des rectangles pour chaque période
for(i in 1:nrow(vacances_hiver)){
  x_start <- 2020 + as.numeric(vacances_hiver$start[i] - as.Date("2020-01-01"))/365
  x_end   <- 2020 + as.numeric(vacances_hiver$end[i] - as.Date("2020-01-01"))/365
  rect(xleft = x_start, xright = x_end, 
       ybottom = par("usr")[3], ytop = par("usr")[4], 
       col = rgb(0.4,0.6,0.9,0.5), border = NA)
}

# Ajouter un encadrement pour les vacances été
## Ajouter des rectangles pour chaque période
for(i in 1:nrow(vacances_ete)){
  x_start <- 2020 + as.numeric(vacances_ete$start[i] - as.Date("2020-01-01"))/365
  x_end   <- 2020 + as.numeric(vacances_ete$end[i] - as.Date("2020-01-01"))/365
  rect(xleft = x_start, xright = x_end, 
       ybottom = par("usr")[3], ytop = par("usr")[4], 
       col = rgb(1,0.7,0.3,0.5), border = NA)
}

# Ajouter un encadrement pour les vacances paque
## Ajouter des rectangles pour chaque période
for(i in 1:nrow(vacances_paques)){
  x_start <- 2020 + as.numeric(vacances_paques$start[i] - as.Date("2020-01-01"))/365
  x_end   <- 2020 + as.numeric(vacances_paques$end[i] - as.Date("2020-01-01"))/365
  rect(xleft = x_start, xright = x_end, 
       ybottom = par("usr")[3], ytop = par("usr")[4], 
       col = rgb(1,0.5,0.5,0.5), border = NA)
}

# Ajouter un encadrement pour les vacances carnaval
## Ajouter des rectangles pour chaque période
for(i in 1:nrow(vacances_carnaval)){
  x_start <- 2020 + as.numeric(vacances_carnaval$start[i] - as.Date("2020-01-01"))/365
  x_end   <- 2020 + as.numeric(vacances_carnaval$end[i] - as.Date("2020-01-01"))/365
  rect(xleft = x_start, xright = x_end, 
       ybottom = par("usr")[3], ytop = par("usr")[4], 
       col = rgb(0.4,0.8,0.4,0.3), border = NA)
}


# Ajouter un encadrement pour les vacances toussaint
## Ajouter des rectangles pour chaque période
for(i in 1:nrow(vacances_toussaint)){
  x_start <- 2020 + as.numeric(vacances_toussaint$start[i] - as.Date("2020-01-01"))/365
  x_end   <- 2020 + as.numeric(vacances_toussaint$end[i] - as.Date("2020-01-01"))/365
  rect(xleft = x_start, xright = x_end, 
       ybottom = par("usr")[3], ytop = par("usr")[4], 
       col = rgb(0.7,0.4,0.8,0.5), border = NA)
}

#legend
legend("topright", 
       legend = c("Confinement du 18 mars 2020", 
                  "Vacances hiver", 
                  "Vacances carnaval", 
                  "Vacances Pâques", 
                  "Vacances été", 
                  "Vacances Toussaint"),
       col = c("red", 
                 rgb(0.4,0.6,0.9,0.5),
               rgb(0.4,0.8,0.5,0.5),
               rgb(1,0.5,0.5,0.5),
               rgb(1,0.7,0.3,0.5),
               rgb(0.7,0.4,0.8,0.5)),
       lty = c(2, NA, NA, NA, NA, NA),
       pch = c(NA, 15, 15, 15, 15, 15),
       pt.cex = 1.2,
       cex = 0.8,
       bty = "o",
       bg = "white")
```

**L'influence de la saisonnalité sur l'affluence dans les parcs**

Comme imaginé, l'affluence dans les parcs varie tout d'abord selon les saisons. Au début d'année, lorsque les températures sont au plus bas, le nombre de fréquentations est au plus bas. Ensuite, au fur et à mesure que les températures s'adoucissent, les parcs se remplissent petit à petit jusqu'à avoir une fréquentation maximum en plein été. Au début de l'automne, les températures diminuent à nouveau et les parcs se vident petit à petit.

**L'influence des vacances scolaires sur l'affluence dans les parcs**

En période de vacances scolaires, les parcs sont généralements plus remplis. En effet, les jeunes ne sont pas à l'école de la journée et les parents prennent parfois congés également à ces memes périodes pour profiter en famille de moments en extérieur. Evidemment, toutes les vacances scolaires n'ont pas le même impact. Même si les enfants et parents disposent de plus de temps libre, les vacances d'automne/hiver ne permettent pas une réelle augmentation de l'affluence dans les parcs puisque les températures ne le permettent pas.

**L'influence du COVID-19 sur l'affluence dans les parcs**

Le premier confinement a marqué un tournant majeurs dans la vie quotidienne des habitants. A partir de mars 2020, dès l'annonce du confinement, une importante chute est visible sur le graphique. En effet, les mesures ont été strictes: il était nécéssaire d'avoir une raison valable pour être autorisé à sortir de chez soi et surtout, la majorité des espaces publics ont été fermés pour des mesures sanitaires.

Au déconfinement, l'arrivée des beaux jours et l'envie de sortir de chez soi après y avoir été enfermé sur une longue période montrent une augmentation très rapide de l'affluence dans les parcs. Pour le moment, les mesures sanitaires tels que le port du masque et les distances de sécurité permettent à la population de profiter des espaces publics tout en se sentant en sécurité.

En novembre 2020, le deuxième confinement a lieu. De nouvelles mesures sont prises mais elles sont beaucoup plus souples cette fois: les distances de sécurités doivent toujours être respectées, les masques doivent toujours être portés mais les espaces publics extérieurs restent ouverts pour la plupart. Les mesures de déplacement sont également moins strictes, la population profite de son heure de déplacement à moins d'un kilomètre de chez soi pour profiter des espaces publics à proximité lorsqu'il y en a ou lorsque c'est possible. L'impact de ce confinement est donc moindre.

Après ce deuxième confinement, on observe une légère hausse de fréquentation, montrant que malgré tout, la population est contente de retrouver pleinement sa liberté.

#### Analyse de la différence de fréquentation entre la semaine et les weekends

Ayant remarqués que les vacances scolaires influencaient

### Impact sur les pharmacies

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->
